api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('data', views.GenericDataList.as_view(), name='home'),
]

dummyproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('', include('user.urls', namespace='user'))
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.home, name='home'),
    path('create_data', views.create_dummy_data, name='create_dummy_data')
    

]

api/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    id = models.CharField(primary_key=True, max_length=9)
    real_name = models.CharField(max_length=50)
    tz = models.CharField(default='Asia/Kolkata', max_length=40)

    def __str__(self):
        return self.real_name

class ActivityPeriod(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='activity_period')

    class Meta:
        verbose_name = 'ActivityPeriod'
        verbose_name_plural = 'ActivityPeriods'

    def __str__(self):
        return "{'start_time': %s, 'end_time': %s}" %(repr(self.start_time.strftime("%b %d, %Y %I:%M%p")), repr(self.end_time.strftime("%b %d, %Y %I:%M%p")))

user/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render, redirect
from .models import Users, ActivityPeriod
from django.views.decorators.csrf import csrf_exempt
import random
import pytz
import datetime
from .serializers import UserSerializer
from rest_framework.views import APIView
from rest_framework import generics, mixins
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework import generics, mixins

# class GenericDataList(generics.GenericAPIView, mixins.ListModelMixin):
#     serializer_class = UserSerializer
#     queryset = Users.objects.all()
#     renderer_classes = [JSONRenderer]

#     def get(self, request):
#         # user_data = Users.objects.all()
#         # context = {'user':user_data}
#         return self.list(request)

class GenericDataList(APIView):

    renderer_classes = [JSONRenderer]

    def get(self, request):
        user_data = Users.objects.all()

        serializer = UserSerializer(user_data, many=True)
        if serializer.data:
            for each in serializer.data:
                if "activity_period" in each.keys():
                    for i in range(0,len(each['activity_period'])):
                        each['activity_period'][i] = eval(each['activity_period'][i])
            data = {"ok":"true", "members":serializer.data}
        else:
            data = {"ok":"false", "members": None}
        return Response(data)

user/views.py
"""module contains all the functions for frontend interaction"""
from django.shortcuts import render, redirect
from api.models import Users, ActivityPeriod
from django.views.decorators.csrf import csrf_exempt
import random
import string
import pytz
import datetime
import requests
from api.serializers import UserSerializer
from rest_framework.views import APIView
from rest_framework import generics, mixins
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response


def home(request):
    """
    Url for home function.

    :http relative-url: /
    :http-method :GET
    """
    if request.method == 'GET':
        url = 'http://'+request.get_host()+'/api/data'
        headers = {
            'Content-Type': 'application/json',
        }
        response = requests.get(url=url, headers=headers)
        if response.json()['members']:
            context = {'user': response.json()}
        else:
            context = {'user': None}
        return render(request, 'home.html', context)

@csrf_exempt 
def create_dummy_data(request):
    """
    Function to populate database.

    :http relative-url: /create_data
    :http-method :POST
    """
    real_name = request.POST.get('name')
    tz = random.choice(pytz.all_timezones)
    letters = string.ascii_lowercase+'0123456789'
    id =  ''.join(random.choice(letters) for i in range(0,9))
    user = Users.objects.create(id=id,real_name=real_name, tz=tz)
    num_activity_periods = random.randint(1,5)
    for i in range(0, num_activity_periods):
        start_time = datetime.datetime.today() - datetime.timedelta(days=random.randrange(8))
        end_time = start_time + datetime.timedelta(days=random.randrange(10))
        ActivityPeriod.objects.create(start_time=start_time,end_time=end_time, user=user)
    return redirect('user:home')
    

templates/base.html
{% load static %}
<html lang="en">

  ​
  
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> FULLTHROTTLE LABS TEST </title>
    
      <script
  
      src="https://code.jquery.com/jquery-1.12.4.min.js"
  
      integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  
      crossorigin="anonymous"></script>
  
      
  
      <script src="https://code.highcharts.com/highcharts.src.js"></script>
  
  ​
  
      <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  
  ​
  
      <title>Expense App</title>
  
  ​
  
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  
      
  
      <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
  
            integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  
      
  
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  
              integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  
              crossorigin="anonymous"></script>
  
      
  
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  
              integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  
              crossorigin="anonymous"></script>
  
      
  
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  
              integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  
              crossorigin="anonymous"></script>  
  ​<style>
    .navbar {
    margin-top: -25;
    position: relative;
    display: flex;
    align-items: center;
    padding: .5rem 2rem;
    }
   
    body{
      height: 900px;
      }

      .image{
        background-image: url("https://images.all-free-download.com/images/graphiclarge/light_wallpaper_background_235790.jpg");
        background-repeat: no-repeat;
        height:120%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        }  
footer {
    display: block;
    background-color:rgb(66, 64, 64);
    color:gainsboro;
    }
{% block style %}
{% endblock style%}    
</style>   
</head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">FULLTHROTTLE LABS ASSIGNMENT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
      </nav>
      <div class="image">
      {% block body %}
      {% endblock %}  ​
      </div>
  
</body>
<footer class="page-footer font-small black">
  <div class="footer-copyright text-center py-3">© 2020 Copyright
  </div>
</footer>
</html>

user/templates/home.html
{% extends 'base.html' %}
{% block body %}
<style>
  
  .create {
    margin-left: 10rem;
    padding-top: 3rem;
}
  
</style>
    <form class="create" action="{% url 'user:create_dummy_data' %}" method="post">
        Username: <input type="text" name="name" required>
        <button type="submit">Create data</button>
      </form>  
    {% if user %}
    <p id="demo"></p>
    <button type="submit" onclick="show_json()">Json View</button><br>
        {% for key,value in user.items %}
            {% ifequal key 'members' %}
            {% for each in value %}
            <div class="card" style="width: 100rem; margin-left: 7rem;">
                <div class="card-body">
                  <h5 class="card-title">Member</h5>
                  <p class="card-text">{% for val_key,val_value in each.items %}
                  {{val_key}}:{{val_value}}<br>
                  {% endfor %}
                  </p>
                </div>
              </div>                    
            {% endfor %}
            {% endifequal %}
        {% endfor %}
    {% else %}
    <h4>No data<h4>
    {% endif %}
    
    <script>

        function show_json() {      
          document.getElementById("demo").innerHTML = '{{user}}';

        }
        </script>
        
{% endblock %}